version: '3.0'
services:
        api:
                restart: always
                build: ./src
                container_name: 'fastPy'
                ports:
                        - 8000:8000
                volumes: 
                        - ./src:/src
                depends_on:
                        - db
        db:
                restart: always
                image: mariadb:latest
                ports: 
                        - 3306:3306
                container_name: 'fastpy_Maindb'
                environment: 
                        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                        MYSQL_DATABASE: ${MYSQL_DATABASE}
                        MYSQL_USER: ${MYSQL_USERNAME}
                        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                volumes: 
                        - ./docker/db/data:/var/lib/mysql
                        - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
                        - ./docker/db/sql:/docker-entrypoint-initdb.d
                
